<a href="https://colab.research.google.com/github/Priscilla-c179/python_data-science/blob/main/notebooks/M2Lab1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Welcome to our Lab practice!

This lab is all about the package, Numpy. Are you ready? Let's go!

You will find some small tasks in sections below.

> Try to figure out by yourself, or search for references. Being able to search and find information needed is an important skill that benefits you and your career for a long time.





## Import the package and rename it as np

In [8]:
import numpy as np

## Array Creation

### Task: Create a numpy array from a list of integers

In [9]:
np.array([1,3,5,78])

array([ 1,  3,  5, 78])

### Task: Create a numpy array of size 6, filled with zeros

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

###Task: Create a numpy array of size 6, filled with ones

In [11]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

###Task: Create a numpy array with values from 0 to 10

In [12]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###Task: Create a numpy matrix of 2*3 integers, filled with zeros

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

###Task: Create a numpy matrix of 3*2 integers, filled with ones

In [14]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

###Task: Create a numpy matrix of 3*2 integers, filled with random integers in [0, 10]

In [15]:
np.random.randint(0,10,(3,2))

array([[9, 9],
       [0, 9],
       [2, 8]])

###Task: Create a numpy matrix of 100 * 2, filled with random float value in [0, 1]

In [16]:
np.random.uniform(0,1,(100,2))

array([[0.01169715, 0.71996878],
       [0.23896175, 0.76801284],
       [0.88219114, 0.10272721],
       [0.93652973, 0.46698553],
       [0.69146748, 0.50651056],
       [0.14010947, 0.74621127],
       [0.85247634, 0.59195291],
       [0.23831384, 0.7147769 ],
       [0.33545149, 0.07928584],
       [0.741164  , 0.7080396 ],
       [0.57891384, 0.48575895],
       [0.95232594, 0.84711428],
       [0.89312773, 0.69840165],
       [0.9351156 , 0.224647  ],
       [0.62354931, 0.84559026],
       [0.2325145 , 0.64656939],
       [0.11337164, 0.99609051],
       [0.74680217, 0.70694532],
       [0.65540154, 0.58697934],
       [0.36888482, 0.55787565],
       [0.55014859, 0.1804355 ],
       [0.91632319, 0.40462438],
       [0.94504426, 0.96024671],
       [0.93067693, 0.78171532],
       [0.50333075, 0.25036981],
       [0.33112676, 0.32549513],
       [0.33091969, 0.5123958 ],
       [0.71176562, 0.78425075],
       [0.36867467, 0.05432532],
       [0.65666599, 0.5148942 ],
       [0.

###Task: Create a numpy matrix of 2 * 3 * 4, filled with integers from 1 to 24.

In [17]:
np.arange(1,25).reshape(2,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

## Array Indexing

### Task: Let X be a numpy array, and X = np.array([1, 2, 3, 4, 5])

In [18]:
x=np.array([1,2,3,4,5])

### Task: Show the first element of X

In [19]:
x[0]

np.int64(1)

### Task: Show the last element of X

In [20]:
x[-1]

np.int64(5)

### Task: Show the first 3 elements of X

In [21]:
x[:3]

array([1, 2, 3])

###Task: Show the last 3 elements of X

In [22]:
x[-3:]

array([3, 4, 5])

###Task: Show the elements of X whose index is odd (1, 3, 5, ...)

In [23]:
x[[0,2,4]]

array([1, 3, 5])

###Task: Show the elements of X except the last one

In [24]:
x[: -1]

array([1, 2, 3, 4])

### Task: Let X be a numpy matrix with dimension 3 * 4, and filled from 0 to 11.

In [25]:
x=np.arange(0,12).reshape(3,4)

In [26]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

###Task: Show the first row of X

In [27]:
x[0]

array([0, 1, 2, 3])

###Task: Show the first column of X

In [40]:
x[:,0]

array([0, 4, 8])

###Task: Show the first element of the first row of X

In [29]:
x[0]

array([0, 1, 2, 3])

###Task: Show the last row of X

In [30]:
x[-1]

array([ 8,  9, 10, 11])

###Task: Show the last column of X

In [31]:
x[:,-1]

array([ 3,  7, 11])

###Task: Show the last element of the last row of X

In [32]:
x[-1][-1]

np.int64(11)

###Task: Show all the rows except the last row of X

In [33]:
x[-1]

array([ 8,  9, 10, 11])

###Task: Show all the columns except the last column of X

In [34]:
x[: -1]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### Task: Show the first two elements of the first two rows

In [35]:
x[:2,:2]

array([[0, 1],
       [4, 5]])

## Array Statistics

###Task: Create a numpy array X, print the sum, mean, std, var, max, min of it

In [42]:
x=np.arange(20)
print(np.sum(x))
print(np.mean(x))
print(np.std(x))
print(np.var(x))
print(np.max(x))
print(np.min(x))

190
9.5
5.766281297335398
33.25
19
0


###Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st row of it.

In [43]:
x=np.arange(12).reshape(3,4)
print(np.sum(x[0]))
print(np.mean(x[0]))
print(np.std(x[0]))
print(np.var(x[0]))
print(np.max(x[0]))

6
1.5
1.118033988749895
1.25
3


###Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st column of it.

In [44]:
x=np.arange(12).reshape(3,4)
print(np.sum(x[:,0]))
print(np.mean(x[:,0]))
print(np.std(x[:,0]))
print(np.var(x[:,0]))
print(np.max(x[:,0]))

12
4.0
3.265986323710904
10.666666666666666
8


## Array Linear Algebra

###Task: Create two numpy matrix X with 2 * 2, and Y with 2 * 2. Practice Linear Algebra operations, such as +, -, *, .T, @, etc.

In [45]:
x=np.arange(4).reshape(2,2)
y=np.arange(4,8).reshape(2,2)
print(x+y)
print(x-y)
print(x*y)
print(x.T)

[[ 4  6]
 [ 8 10]]
[[-4 -4]
 [-4 -4]]
[[ 0  5]
 [12 21]]
[[0 2]
 [1 3]]
